// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	exchange "github.com/Confialink/wallet-currencies/internal/services/exchange"
	mock "github.com/stretchr/testify/mock"
)

// RateReceiver is an autogenerated mock type for the RateReceiver type
type RateReceiver struct {
	mock.Mock
}

// Set provides a mock function with given fields: rate
func (_m *RateReceiver) Set(rate exchange.Rate) error {
	ret := _m.Called(rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(exchange.Rate) error); ok {
		r0 = rf(rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
