// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	exchange "github.com/Confialink/wallet-currencies/internal/services/exchange"
	mock "github.com/stretchr/testify/mock"
)

// RateSource is an autogenerated mock type for the RateSource type
type RateSource struct {
	mock.Mock
}

// FindRate provides a mock function with given fields: base, reference
func (_m *RateSource) FindRate(base string, reference string) (exchange.Rate, error) {
	ret := _m.Called(base, reference)

	var r0 exchange.Rate
	if rf, ok := ret.Get(0).(func(string, string) exchange.Rate); ok {
		r0 = rf(base, reference)
	} else {
		r0 = ret.Get(0).(exchange.Rate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(base, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
