FROM alpine:3.11

RUN apk add ca-certificates tzdata
WORKDIR /app

COPY zoneinfo.zip /app/zoneinfo.zip
ENV ZONEINFO /app/zoneinfo.zip

COPY ./build/service_currencies /app/service_currencies

ENTRYPOINT ["/app/service_currencies"]