// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	exchange "github.com/Confialink/wallet-currencies/internal/services/exchange"
	mock "github.com/stretchr/testify/mock"
)

// CurrencySourceFactory is an autogenerated mock type for the CurrencySourceFactory type
type CurrencySourceFactory struct {
	mock.Mock
}

// Init provides a mock function with given fields:
func (_m *CurrencySourceFactory) Init() (exchange.RateSource, error) {
	ret := _m.Called()

	var r0 exchange.RateSource
	if rf, ok := ret.Get(0).(func() exchange.RateSource); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exchange.RateSource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
