// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/currencies/currencies.proto

package currencies

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CurrencyReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyReq) Reset()         { *m = CurrencyReq{} }
func (m *CurrencyReq) String() string { return proto.CompactTextString(m) }
func (*CurrencyReq) ProtoMessage()    {}
func (*CurrencyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a96cda79409edd23, []int{0}
}

func (m *CurrencyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyReq.Unmarshal(m, b)
}
func (m *CurrencyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyReq.Marshal(b, m, deterministic)
}
func (m *CurrencyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyReq.Merge(m, src)
}
func (m *CurrencyReq) XXX_Size() int {
	return xxx_messageInfo_CurrencyReq.Size(m)
}
func (m *CurrencyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyReq.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyReq proto.InternalMessageInfo

func (m *CurrencyReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CurrencyReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CurrencyResp struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	DecimalPlaces        int32    `protobuf:"varint,4,opt,name=decimalPlaces,proto3" json:"decimalPlaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyResp) Reset()         { *m = CurrencyResp{} }
func (m *CurrencyResp) String() string { return proto.CompactTextString(m) }
func (*CurrencyResp) ProtoMessage()    {}
func (*CurrencyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a96cda79409edd23, []int{1}
}

func (m *CurrencyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyResp.Unmarshal(m, b)
}
func (m *CurrencyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyResp.Marshal(b, m, deterministic)
}
func (m *CurrencyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyResp.Merge(m, src)
}
func (m *CurrencyResp) XXX_Size() int {
	return xxx_messageInfo_CurrencyResp.Size(m)
}
func (m *CurrencyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyResp.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyResp proto.InternalMessageInfo

func (m *CurrencyResp) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CurrencyResp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CurrencyResp) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *CurrencyResp) GetDecimalPlaces() int32 {
	if m != nil {
		return m.DecimalPlaces
	}
	return 0
}

type CurrenciesResp struct {
	Currencies           []*CurrencyResp `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CurrenciesResp) Reset()         { *m = CurrenciesResp{} }
func (m *CurrenciesResp) String() string { return proto.CompactTextString(m) }
func (*CurrenciesResp) ProtoMessage()    {}
func (*CurrenciesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a96cda79409edd23, []int{2}
}

func (m *CurrenciesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrenciesResp.Unmarshal(m, b)
}
func (m *CurrenciesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrenciesResp.Marshal(b, m, deterministic)
}
func (m *CurrenciesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrenciesResp.Merge(m, src)
}
func (m *CurrenciesResp) XXX_Size() int {
	return xxx_messageInfo_CurrenciesResp.Size(m)
}
func (m *CurrenciesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrenciesResp.DiscardUnknown(m)
}

var xxx_messageInfo_CurrenciesResp proto.InternalMessageInfo

func (m *CurrenciesResp) GetCurrencies() []*CurrencyResp {
	if m != nil {
		return m.Currencies
	}
	return nil
}

type CurrenciesRateValueRequest struct {
	CurrencyIdFrom       uint32   `protobuf:"varint,1,opt,name=currencyIdFrom,proto3" json:"currencyIdFrom,omitempty"`
	CurrencyIdTo         uint32   `protobuf:"varint,2,opt,name=currencyIdTo,proto3" json:"currencyIdTo,omitempty"`
	CurrencyCodeFrom     string   `protobuf:"bytes,3,opt,name=currencyCodeFrom,proto3" json:"currencyCodeFrom,omitempty"`
	CurrencyCodeTo       string   `protobuf:"bytes,4,opt,name=currencyCodeTo,proto3" json:"currencyCodeTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrenciesRateValueRequest) Reset()         { *m = CurrenciesRateValueRequest{} }
func (m *CurrenciesRateValueRequest) String() string { return proto.CompactTextString(m) }
func (*CurrenciesRateValueRequest) ProtoMessage()    {}
func (*CurrenciesRateValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a96cda79409edd23, []int{3}
}

func (m *CurrenciesRateValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrenciesRateValueRequest.Unmarshal(m, b)
}
func (m *CurrenciesRateValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrenciesRateValueRequest.Marshal(b, m, deterministic)
}
func (m *CurrenciesRateValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrenciesRateValueRequest.Merge(m, src)
}
func (m *CurrenciesRateValueRequest) XXX_Size() int {
	return xxx_messageInfo_CurrenciesRateValueRequest.Size(m)
}
func (m *CurrenciesRateValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrenciesRateValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrenciesRateValueRequest proto.InternalMessageInfo

func (m *CurrenciesRateValueRequest) GetCurrencyIdFrom() uint32 {
	if m != nil {
		return m.CurrencyIdFrom
	}
	return 0
}

func (m *CurrenciesRateValueRequest) GetCurrencyIdTo() uint32 {
	if m != nil {
		return m.CurrencyIdTo
	}
	return 0
}

func (m *CurrenciesRateValueRequest) GetCurrencyCodeFrom() string {
	if m != nil {
		return m.CurrencyCodeFrom
	}
	return ""
}

func (m *CurrenciesRateValueRequest) GetCurrencyCodeTo() string {
	if m != nil {
		return m.CurrencyCodeTo
	}
	return ""
}

type CurrenciesRateValueResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrenciesRateValueResponse) Reset()         { *m = CurrenciesRateValueResponse{} }
func (m *CurrenciesRateValueResponse) String() string { return proto.CompactTextString(m) }
func (*CurrenciesRateValueResponse) ProtoMessage()    {}
func (*CurrenciesRateValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a96cda79409edd23, []int{4}
}

func (m *CurrenciesRateValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrenciesRateValueResponse.Unmarshal(m, b)
}
func (m *CurrenciesRateValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrenciesRateValueResponse.Marshal(b, m, deterministic)
}
func (m *CurrenciesRateValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrenciesRateValueResponse.Merge(m, src)
}
func (m *CurrenciesRateValueResponse) XXX_Size() int {
	return xxx_messageInfo_CurrenciesRateValueResponse.Size(m)
}
func (m *CurrenciesRateValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrenciesRateValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrenciesRateValueResponse proto.InternalMessageInfo

func (m *CurrenciesRateValueResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CurrenciesRateResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ExchangeMargin       string   `protobuf:"bytes,2,opt,name=exchangeMargin,proto3" json:"exchangeMargin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrenciesRateResponse) Reset()         { *m = CurrenciesRateResponse{} }
func (m *CurrenciesRateResponse) String() string { return proto.CompactTextString(m) }
func (*CurrenciesRateResponse) ProtoMessage()    {}
func (*CurrenciesRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a96cda79409edd23, []int{5}
}

func (m *CurrenciesRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrenciesRateResponse.Unmarshal(m, b)
}
func (m *CurrenciesRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrenciesRateResponse.Marshal(b, m, deterministic)
}
func (m *CurrenciesRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrenciesRateResponse.Merge(m, src)
}
func (m *CurrenciesRateResponse) XXX_Size() int {
	return xxx_messageInfo_CurrenciesRateResponse.Size(m)
}
func (m *CurrenciesRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrenciesRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrenciesRateResponse proto.InternalMessageInfo

func (m *CurrenciesRateResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CurrenciesRateResponse) GetExchangeMargin() string {
	if m != nil {
		return m.ExchangeMargin
	}
	return ""
}

func init() {
	proto.RegisterType((*CurrencyReq)(nil), "velmie.wallet.currencies.CurrencyReq")
	proto.RegisterType((*CurrencyResp)(nil), "velmie.wallet.currencies.CurrencyResp")
	proto.RegisterType((*CurrenciesResp)(nil), "velmie.wallet.currencies.CurrenciesResp")
	proto.RegisterType((*CurrenciesRateValueRequest)(nil), "velmie.wallet.currencies.CurrenciesRateValueRequest")
	proto.RegisterType((*CurrenciesRateValueResponse)(nil), "velmie.wallet.currencies.CurrenciesRateValueResponse")
	proto.RegisterType((*CurrenciesRateResponse)(nil), "velmie.wallet.currencies.CurrenciesRateResponse")
}

func init() {
	proto.RegisterFile("rpc/currencies/currencies.proto", fileDescriptor_a96cda79409edd23)
}

var fileDescriptor_a96cda79409edd23 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0xdd, 0x4e, 0xe2, 0x40,
	0x14, 0xc7, 0x53, 0x0a, 0xec, 0x72, 0xf8, 0xd8, 0xcd, 0x64, 0x43, 0x1a, 0x36, 0x9b, 0xdd, 0x34,
	0x2b, 0x21, 0x5e, 0x54, 0x05, 0x7d, 0x01, 0x48, 0x30, 0x5e, 0x90, 0x98, 0x89, 0x21, 0xc4, 0x78,
	0x33, 0x4e, 0x4f, 0xa0, 0x49, 0x69, 0x4b, 0x5b, 0x50, 0x6e, 0xbd, 0xf6, 0x91, 0x7c, 0x15, 0xdf,
	0xc5, 0x61, 0x28, 0xb4, 0x7c, 0xa8, 0x35, 0x7a, 0x37, 0xe7, 0x37, 0x73, 0xfe, 0xe7, 0x7f, 0xce,
	0x81, 0xc2, 0x5f, 0xdf, 0xe3, 0x47, 0x7c, 0xea, 0xfb, 0xe8, 0x70, 0x0b, 0x83, 0xc4, 0xd1, 0xf0,
	0x7c, 0x37, 0x74, 0x89, 0x36, 0x43, 0x7b, 0x6c, 0xa1, 0x71, 0xc7, 0x6c, 0x1b, 0x43, 0x23, 0xbe,
	0xd7, 0x4f, 0xa0, 0xd8, 0x59, 0x46, 0x73, 0x8a, 0x13, 0x52, 0x81, 0x8c, 0x65, 0x6a, 0xca, 0x3f,
	0xa5, 0x51, 0xa6, 0xe2, 0x44, 0x08, 0x64, 0xb9, 0x6b, 0xa2, 0x96, 0x11, 0xa4, 0x40, 0xe5, 0x59,
	0xf7, 0xa0, 0x14, 0xa7, 0x04, 0x5e, 0x9a, 0x1c, 0x52, 0x85, 0x3c, 0xe3, 0xa1, 0x35, 0x43, 0x4d,
	0x15, 0xf4, 0x3b, 0x8d, 0x22, 0xf2, 0x1f, 0xca, 0x26, 0x72, 0x6b, 0xcc, 0xec, 0x4b, 0x9b, 0x71,
	0x0c, 0xb4, 0xac, 0xb8, 0xce, 0xd1, 0x4d, 0xa8, 0x0f, 0xa0, 0xd2, 0x59, 0x5b, 0x96, 0x35, 0xbb,
	0x00, 0x71, 0x13, 0xa2, 0xb6, 0xda, 0x28, 0x36, 0xeb, 0xc6, 0x6b, 0x5d, 0x1a, 0x49, 0xbf, 0x34,
	0x91, 0xa9, 0x3f, 0x29, 0x50, 0x4b, 0x48, 0xb3, 0x10, 0xfb, 0xcc, 0x9e, 0xa2, 0x18, 0xc5, 0x14,
	0x83, 0x90, 0xd4, 0xa1, 0x12, 0x3d, 0x9e, 0x5f, 0x98, 0x5d, 0xdf, 0x1d, 0x47, 0x6d, 0x6e, 0x51,
	0xa2, 0x43, 0x29, 0x26, 0x57, 0xae, 0x6c, 0xbd, 0x4c, 0x37, 0x18, 0x39, 0x84, 0x9f, 0xab, 0xb8,
	0x23, 0x46, 0x22, 0xd5, 0x54, 0x39, 0xa2, 0x1d, 0x9e, 0xac, 0xbb, 0x60, 0x42, 0x31, 0x2b, 0x5f,
	0x6e, 0x51, 0xbd, 0x05, 0xbf, 0xf7, 0xba, 0x0f, 0x3c, 0xd7, 0x09, 0x90, 0xfc, 0x82, 0xdc, 0x6c,
	0x01, 0xa4, 0xeb, 0x02, 0x5d, 0x06, 0x7a, 0x1f, 0xaa, 0x9b, 0x49, 0x6f, 0xbf, 0x5f, 0x98, 0xc1,
	0x7b, 0x3e, 0x62, 0xce, 0x10, 0x7b, 0xcc, 0x1f, 0x5a, 0x4e, 0xb4, 0xd9, 0x2d, 0xda, 0x7c, 0x56,
	0xe1, 0xc7, 0x6a, 0xd0, 0x5d, 0x0c, 0xf9, 0x08, 0x7d, 0x32, 0x80, 0x6f, 0xe7, 0x18, 0xf6, 0x98,
	0xe5, 0x90, 0x83, 0x34, 0xeb, 0x99, 0xd4, 0x52, 0x6e, 0x91, 0xdc, 0x40, 0x51, 0x28, 0xaf, 0xd0,
	0x57, 0xab, 0x3f, 0x28, 0xa0, 0xc5, 0xf2, 0xd1, 0x9c, 0xda, 0x72, 0xec, 0x01, 0x39, 0x7d, 0x57,
	0x64, 0xcf, 0x6f, 0xa9, 0x76, 0x9c, 0x36, 0x6b, 0xbd, 0x8e, 0x47, 0x05, 0xfe, 0xec, 0x98, 0x90,
	0x9a, 0x9f, 0x73, 0x72, 0xf6, 0xc1, 0xac, 0xa5, 0x9d, 0x76, 0xe9, 0x3a, 0xf1, 0xcf, 0xb9, 0xcd,
	0xcb, 0x2f, 0x4b, 0xeb, 0x25, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xd3, 0xab, 0xe1, 0x7c, 0x04, 0x00,
	0x00,
}
